### ISSUE TITLE
Pots spawning in bottom of ocean

### ISSUE THREAD

**Issue by SafsoufaS** [Laton95/Pyramid-Plunder#2]
I was playing in a large mod pack along with my sister and we kept finding these pots on the bottom of the ocean and we thought it was really unbalanced, as we have never gone mining yet and suddenly have 6 diamonds with us. They keep spawning on the sea bed, sometimes just a short distance from one another. This may have something to do with Biomes o' plenty and tropicraft, since they add modded biomes and so the height of the sea bed may be below 50. I just wanted to bring this up

**Comment by Laton95** [comment]
This is fixed in the 1.14 versions, but unfortunately I don't have a way of fixing it in 1.12.
