### ISSUE TITLE
Server crash while playing

### ISSUE THREAD

**Issue by Darkfiend009** [Laton95/Pyramid-Plunder#4]
Crash Log: https://pastebin.com/wU0Zcyc0

Minecraft 1.15.2
Forge: 31.1.74
Pyramid Plunder: 1.15.2-1.0

Server crashed when loading new chunks or loading a new dimension.

**Comment by Laton95** [comment]
Looks like 1.15 changed more things than I thought, thanks for bringing these two things to my attention.

Edit: although looking more into it this isn't a 1.15 thing. I'm shocked that this particular circumstance actually happened but it should be an easy fix
